#52 Login using Identity library
ITU-BDSA2024-GROUP1/Chirp pull request #60
Opened 2024-11-01 13:06 UTC by BirdyDK

2024-11-01 17:33 UTC, Emilbks requested changes
ada

2024-11-01 17:48 UTC, CptShini reviewed
Looks very fine, quite epic.

However... I don't really understand the sudden change to using strings for AuthorId's everywhere in the code, which I'd love to know why we're doing lol.

Secondly, you changed the Environment variable code I wrote, and it's actually a bit faulty now :/ as the environment string can in fact be null, which I (for good reasons) test for.

2024-11-01 18:11 UTC, BirdyDK commented
Thanks for the feedback. I changed back the environment variable code.

The reason why I have changed all of the ID attributes and variables is that our Author domain is now inheriting from IdentityUser, which has Id as a string.

2024-11-03 01:00 UTC, Emilbks approved these changes

2024-11-03 09:05 UTC, CptShini approved these changes
Code seems good, adressed the problems I previously had, and registering/logging in works.

2024-11-03 14:57 UTC, Cybermanboss commented on src/Chirp.Razor/Areas/Identity/Pages/Account/Login.cshtml
why keep the outcommented code? is it for later use, or did you just forget to remove it?

2024-11-03 15:17 UTC, Cybermanboss commented on src/Chirp.Razor/Program.cs
you missed the nullable notation for the string in line 73

2024-11-03 15:20 UTC, Cybermanboss commented on src/Chirp.Razor/Program.cs
and line 65 and 88

2024-11-03 15:22 UTC, Cybermanboss commented on src/Chirp.Razor/Program.cs
also github warns about unreachable code, although it is used right after, so just be sure that it works

2024-11-03 15:32 UTC, Cybermanboss approved these changes
there was some very small stuff, which might or might not change whether program.cs file works as intended. but as it runs i will approve

2024-11-03 16:00 UTC, BirdyDK commented on src/Chirp.Razor/Areas/Identity/Pages/Account/Login.cshtml
It is for later use when we setup login with github

2024-11-03 18:50 UTC, BirdyDK commented on src/Chirp.Razor/Program.cs
The places you mentioned are marked as nullable and I assume the code for test enviroment works since the tests work.

2024-11-03 18:50 UTC, merged